# Generated by Django 4.2.2 on 2023-07-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chalkBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(),
        ),
    ]
